In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

df = pd.read_csv("states_all.csv")
df

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,NaN,NaN,731634.0,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,NaN,NaN,122487.0,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,NaN,NaN,673477.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,NaN,NaN,441490.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,NaN,NaN,5254844.0,208.398961,260.892247,196.764414,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,244.243515,288.172322,221.519266,262.720477
1914,2017_RHODE_ISLAND,RHODE_ISLAND,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,237.554934,277.180126,223.353443,269.553823
1915,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,234.043993,274.673821,213.127835,265.767860
1916,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,241.588947,286.376160,221.750123,259.753002
1917,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,236.057019,273.415854,217.316396,271.617023

In [2]:
#1. SORU

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1918 entries, 0 to 1917
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PRIMARY_KEY                   1918 non-null   object
 1   STATE                         1918 non-null   object
 2   YEAR                          1918 non-null   int64
 3   ENROLL                        1224 non-null   float64
 4   TOTAL_REVENUE                 1275 non-null   float64
 5   FEDERAL_REVENUE               1275 non-null   float64
 6   STATE_REVENUE                 1275 non-null   float64
 7   LOCAL_REVENUE                 1275 non-null   float64
 8   TOTAL_EXPENDITURE             1275 non-null   float64
 9   INSTRUCTION_EXPENDITURE       1275 non-null   float64
 10  SUPPORT_SERVICES_EXPENDITURE  1275 non-null   float64
 11  OTHER_EXPENDITURE             1224 non-null   float64
 12  CAPITAL_OUTLAY_EXPENDITURE    1275 non-null   float64
 13  GRADES_PK_G                   1542 non-null   float64
 14  GRADES_KG_G                   1632 non-null   float64
 15  GRADES_4_G                    1632 non-null   float64
 16  GRADES_8_G                    1632 non-null   float64
 17  GRADES_12_G                   1632 non-null   float64
 18  GRADES_1_8_G                  1020 non-null   float64
 19  GRADES_9_12_G                 1071 non-null   float64
 20  GRADES_ALL_G                  1632 non-null   float64
 21  AVG_MATH_4_SCORE              535 non-null    float64
 22  AVG_MATH_8_SCORE              531 non-null    float64
 23  AVG_READING_4_SCORE           532 non-null    float64
 24  AVG_READING_8_SCORE           497 non-null    float64
dtypes: float64(22), int64(1), object(2)
memory usage: 359.7+ KB

In [4]:
def null_degerler(df):
    null_df=pd.DataFrame()
    null_df['yüzde']=df.isnull().sum()*100/df.shape[0]
    null_df['adet']=df.isnull().sum()
    return null_df.sort_values('yüzde',ascending=False)
null_degerler(df)

                                  yüzde  adet
AVG_READING_8_SCORE           74.087591  1421
AVG_MATH_8_SCORE              72.314911  1387
AVG_READING_4_SCORE           72.262774  1386
AVG_MATH_4_SCORE              72.106361  1383
GRADES_1_8_G                  46.819604   898
GRADES_9_12_G                 44.160584   847
ENROLL                        36.183525   694
OTHER_EXPENDITURE             36.183525   694
SUPPORT_SERVICES_EXPENDITURE  33.524505   643
CAPITAL_OUTLAY_EXPENDITURE    33.524505   643
INSTRUCTION_EXPENDITURE       33.524505   643
TOTAL_EXPENDITURE             33.524505   643
LOCAL_REVENUE                 33.524505   643
STATE_REVENUE                 33.524505   643
FEDERAL_REVENUE               33.524505   643
TOTAL_REVENUE                 33.524505   643
GRADES_PK_G                   19.603754   376
GRADES_KG_G                   14.911366   286
GRADES_4_G                    14.911366   286
GRADES_8_G                    14.911366   286
GRADES_12_G                   14.911366   286
GRADES_ALL_G                  14.911366   286
STATE                          0.000000     0
YEAR                           0.000000     0
PRIMARY_KEY                    0.000000     0

In [5]:
#2.SORU- null olanlar sütunun ortalaması ile dolduruldu.

In [6]:
df2=df.copy()
for sutun_adi in df2.columns[3:]:
    df2[sutun_adi].fillna(df2[sutun_adi].mean(), inplace=True)
df2

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,917541.566176,2.678885e+06,3.041770e+05,1.659028e+06,7.156800e+05,2.653798e+06,1.481703e+06,...,57948.000000,58025.000000,41167.000000,577954.717647,282069.084967,7.316340e+05,208.327876,252.187522,207.963517,263.683325
1,1992_ALASKA,ALASKA,1992,917541.566176,1.049591e+06,1.067800e+05,7.207110e+05,2.221000e+05,9.724880e+05,4.983620e+05,...,9748.000000,8789.000000,6714.000000,577954.717647,282069.084967,1.224870e+05,234.797280,278.461453,218.897886,258.859712
2,1992_ARIZONA,ARIZONA,1992,917541.566176,3.258079e+06,2.978880e+05,1.369815e+06,1.590376e+06,3.401580e+06,1.435908e+06,...,55433.000000,49081.000000,37410.000000,577954.717647,282069.084967,6.734770e+05,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,917541.566176,1.711959e+06,1.785710e+05,9.587850e+05,5.746030e+05,1.743022e+06,9.643230e+05,...,34632.000000,36011.000000,27651.000000,577954.717647,282069.084967,4.414900e+05,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,917541.566176,2.626002e+07,2.072470e+06,1.654651e+07,7.641041e+06,2.713883e+07,1.435892e+07,...,418418.000000,363296.000000,270675.000000,577954.717647,282069.084967,5.254844e+06,208.398961,260.892247,196.764414,263.683325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,917541.566176,9.102045e+06,7.677799e+05,4.223743e+06,4.110522e+06,9.206242e+06,4.768010e+06,...,69166.507966,68106.537377,58420.870711,577954.717647,282069.084967,9.139695e+05,244.243515,288.172322,221.519266,262.720477
1914,2017_RHODE_ISLAND,RHODE_ISLAND,2017,917541.566176,9.102045e+06,7.677799e+05,4.223743e+06,4.110522e+06,9.206242e+06,4.768010e+06,...,69166.507966,68106.537377,58420.870711,577954.717647,282069.084967,9.139695e+05,237.554934,277.180126,223.353443,269.553823
1915,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,917541.566176,9.102045e+06,7.677799e+05,4.223743e+06,4.110522e+06,9.206242e+06,4.768010e+06,...,69166.507966,68106.537377,58420.870711,577954.717647,282069.084967,9.139695e+05,234.043993,274.673821,213.127835,265.767860
1916,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,917541.566176,9.102045e+06,7.677799e+05,4.223743e+06,4.110522e+06,9.206242e+06,4.768010e+06,...,69166.507966,68106.537377,58420.870711,577954.717647,282069.084967,9.139695e+05,241.588947,286.376160,221.750123,259.753002
1917,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,917541.566176,9.102045e+06,7.677799e+05,4.223743e+06,4.110522e+06,9.206242e+06,4.768010e+06,...,69166.507966,68106.537377,58420.870711,577954.717647,282069.084967,9.139695e+05,236.057019,273.415854,217.316396,271.617023

In [7]:
df.groupby('YEAR').mean()['TOTAL_REVENUE'][2000]

7443180.784313725

In [8]:
df.groupby('YEAR').mean()

,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,OTHER_EXPENDITURE,CAPITAL_OUTLAY_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
YEAR,,,,,,,,,,,,,,,,,,,,,
1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56782.980392,56269.686275,50990.509804,NaN,NaN,779473.960784,NaN,NaN,NaN,NaN
1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57600.705882,55657.117647,52565.196078,NaN,NaN,784474.764706,NaN,NaN,NaN,NaN
1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59813.843137,55941.313725,51954.392157,NaN,NaN,788013.529412,NaN,NaN,NaN,NaN
1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62394.078431,55950.274510,48495.647059,NaN,NaN,794955.039216,NaN,NaN,NaN,NaN
1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63687.549020,58414.176471,46687.901961,NaN,NaN,808170.254902,NaN,NaN,NaN,NaN
1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64998.549020,59217.058824,46910.901961,NaN,NaN,824448.588235,NaN,NaN,NaN,NaN
1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,1.370149e+06,NaN,4.050078e+05,...,65524.254902,61353.058824,47657.568627,NaN,NaN,839672.784314,218.410116,266.360319,212.712256,263.307067
1993,802054.333333,4.768758e+06,3.086224e+05,2.209300e+06,2.250836e+06,4.788283e+06,2.540431e+06,1.419870e+06,248234.784314,4.096238e+05,...,65904.117647,63711.098039,47530.019608,NaN,NaN,852253.254902,NaN,NaN,NaN,NaN
1994,801383.960784,4.916678e+06,3.272233e+05,2.225664e+06,2.363790e+06,4.954213e+06,2.626080e+06,1.476894e+06,262916.705882,4.041495e+05,...,67175.509804,64750.921569,48775.529412,NaN,NaN,864931.019608,NaN,NaN,NaN,NaN
1995,858973.039216,5.476034e+06,3.546117e+05,2.555041e+06,2.566381e+06,5.526114e+06,2.931096e+06,1.616281e+06,295324.647059,4.765508e+05,...,67266.333333,65810.549020,48767.352941,NaN,NaN,879225.117647,NaN,NaN,NaN,NaN
1996,873930.607843,5.744172e+06,3.647964e+05,2.737296e+06,2.642080e+06,5.838049e+06,3.076873e+06,1.680742e+06,303516.137255,5.445423e+05,...,67720.960784,66717.941176,50714.666667,NaN,NaN,894334.235294,221.479509,270.182528,214.587049,261.412097
1997,888379.745098,6.115397e+06,3.869910e+05,2.940125e+06,2.788281e+06,6.193357e+06,3.245567e+06,1.762159e+06,305274.705882,6.359637e+05,...,68773.666667,66963.019608,52410.431373,557507.058824,251767.843137,904448.960784,NaN,NaN,NaN,NaN
1998,897509.058824,6.504525e+06,4.272517e+05,3.140750e+06,2.936523e+06,6.595780e+06,3.427786e+06,1.873964e+06,318956.098039,7.034032e+05,...,70434.372549,68242.568627,53366.843137,563202.431373,254533.450980,912521.274510,NaN,NaN,NaN,NaN
1999,905101.470588,6.954543e+06,4.747857e+05,3.390289e+06,3.089468e+06,7.068126e+06,3.633184e+06,1.999630e+06,334733.431373,7.937301e+05,...,72281.686275,68568.176471,54541.588235,567115.549020,258153.529412,918767.627451,NaN,NaN,NaN,NaN
2000,910446.705882,7.443181e+06,5.229861e+05,3.650809e+06,3.269385e+06,7.572106e+06,3.883017e+06,2.136325e+06,352342.941176,8.755735e+05,...,72773.078431,69373.078431,54956.725490,572441.117647,261567.490196,925559.588235,224.803526,273.028605,217.612609,262.687292
2001,916296.274510,8.007941e+06,5.612788e+05,3.937915e+06,3.508747e+06,8.176763e+06,4.170963e+06,2.317517e+06,376510.254902,9.593529e+05,...,72448.901961,70900.764706,56134.490196,576228.549020,266215.372549,934606.549020,NaN,NaN,NaN,NaN
2002,923818.196078,8.363705e+06,6.412445e+05,4.066169e+06,3.656291e+06,8.680107e+06,4.408671e+06,2.452548e+06,396852.352941,1.037669e+06,...,71931.705882,72729.313725,58617.823529,578040.117647,272696.215686,944766.392157,NaN,NaN,NaN,NaN
2003,933396.862745,8.777804e+06,7.216835e+05,4.226496e+06,3.829624e+06,9.064218e+06,4.635866e+06,2.606806e+06,409705.098039,9.903809e+05,...,70962.529412,74694.725490,59735.117647,578290.941176,278219.627451,951768.921569,233.874626,276.743875,217.407252,262.503569
2004,938327.117647,9.225277e+06,8.098227e+05,4.276449e+06,4.139006e+06,9.436110e+06,4.807699e+06,2.715620e+06,422406.803922,1.024876e+06,...,70816.431373,74993.529412,60673.509804,577029.764706,284225.960784,956773.823529,NaN,NaN,NaN,NaN
2005,942259.960784,9.741954e+06,8.697107e+05,4.500507e+06,4.371736e+06,9.933855e+06,5.065459e+06,2.869167e+06,441206.921569,1.063179e+06,...,70147.176471,74546.921569,62357.803922,575350.588235,289959.843137,963005.843137,237.053410,277.751964,218.114082,261.774971
2006,947078.980392,1.039160e+07,9.235447e+05,4.760499e+06,4.707552e+06,1.052437e+07,5.330250e+06,3.058888e+06,463564.176471,1.153117e+06,...,70311.588235,73834.803922,64262.764706,575471.352941,293548.215686,966977.294118,NaN,NaN,NaN,NaN
2007,949109.254902,1.109366e+07,9.104578e+05,5.187230e+06,4.995971e+06,1.116970e+07,5.649631e+06,3.236339e+06,489835.686275,1.256719e+06,...,71066.313725,72724.607843,66166.901961,575978.960784,294013.058824,966481.549020,239.147568,280.617942,220.351554,262.154883
2008,949047.392157,1.160464e+07,9.229685e+05,5.508365e+06,5.173303e+06,1.185454e+07,5.975513e+06,3.449190e+06,511990.941176,1.346140e+06,...,71507.764706,72388.137255,66660.568627,575468.509804,292010.607843,965991.607843,NaN,NaN,NaN,NaN
2009,946249.313725,1.177812e+07,1.096081e+06,5.414781e+06,5.267262e+06,1.209353e+07,6.115512e+06,3.503797e+06,531834.450980,1.334207e+06,...,72559.411765,71593.647059,67287.960784,576271.509804,291407.862745,967862.392157,239.517404,282.416645,220.148958,263.478833
2010,946396.254902,1.182120e+07,1.450335e+06,5.053862e+06,5.317006e+06,1.205371e+07,6.219995e+06,3.508137e+06,532313.568627,1.163844e+06,...,72771.392157,71753.039216,68076.235294,580138.823529,290551.176471,970278.058824,NaN,NaN,NaN,NaN
2011,946587.745098,1.195207e+07,1.445229e+06,5.220582e+06,5.286261e+06,1.191374e+07,6.233568e+06,3.517628e+06,531916.490196,1.026307e+06,...,71997.352941,72139.431373,67683.843137,581545.941176,288354.607843,971013.117647,240.477019,283.490464,220.237258,264.824719
2012,945379.392157,1.185719e+07,1.167298e+06,5.302587e+06,5.387305e+06,1.185893e+07,6.207661e+06,3.526431e+06,531786.607843,9.843594e+05,...,72357.333333,72528.960784,68176.960784,584396.490196,288441.274510,975904.274510,NaN,NaN,NaN,NaN
2013,947012.176471,1.192289e+07,1.066444e+06,5.368678e+06,5.487767e+06,1.192948e+07,6.317421e+06,3.562444e+06,545102.784314,9.213200e+05,...,72700.647059,73595.235294,68159.450980,588303.725490,289055.470588,981265.137255,241.891073,283.914996,221.046820,266.680635
2014,948607.529412,1.232629e+07,1.037290e+06,5.663455e+06,5.625549e+06,1.224938e+07,6.481809e+06,3.681058e+06,556592.294118,9.333451e+05,...,72919.078431,73658.921569,68558.509804,590994.627451,291975.745098,986521.196078,NaN,NaN,NaN,NaN
2015,951263.450980,1.281705e+07,1.045230e+06,5.933968e+06,5.837854e+06,1.276276e+07,6.750863e+06,3.811953e+06,568480.588235,1.022395e+06,...,74367.352941,72912.980392,69357.490196,591894.117647,294129.019608,986804.215686,240.233705,281.759044,222.123041,265.007992
2016,952388.764706,1.337367e+07,1.061579e+06,6.234438e+06,6.077655e+06,1.326522e+07,7.011348e+06,3.911124e+06,587423.941176,1.120930e+06,...,75655.607843,73507.941176,70028.254902,593424.176471,295810.784314,991918.803922,NaN,NaN,NaN,NaN
2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75675.980392,73966.196078,71204.901961,NaN,296813.627451,993834.647059,239.202783,281.878993,221.095513,265.632094

In [9]:
df.loc[df['YEAR']==2000,['TOTAL_REVENUE']].fillna(df.loc[df ['YEAR']==2000, ['TOTAL_REVENUE']].mean())

      TOTAL_REVENUE
408    4.885917e+06
409    1.313510e+06
410    5.479168e+06
411    2.844855e+06
412    4.662821e+07
...             ...
1677   7.443181e+06
1737   7.443181e+06
1769   7.443181e+06
1801   7.443181e+06
1875   7.443181e+06

[62 rows x 1 columns]

In [10]:
#3. SORU null olanlar o yılın ortalaması ile dolduruldu.
df['TOTAL_REVENUE'][1276]

nan

In [11]:
df3=df.copy()
yıllar=df3['YEAR'].unique()
def doldur(df3):
       for sutun_adi in df.columns[3:]:
            for yıl in yıllar:
                #df3[sutun_adi].fillna(df3.groupby('YEAR').mean()[sutun_adi][yıllar[i]], inplace=True)
                df3[sutun_adi].fillna(df3.groupby(df3['YEAR']==yıl)[sutun_adi].transform('mean'), inplace=True)

doldur(df3)
df3

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,920824.648047,2.678885e+06,3.041770e+05,1.659028e+06,7.156800e+05,2.653798e+06,1.481703e+06,...,57948.0,58025.000000,41167.000000,577954.717647,282069.084967,7.316340e+05,208.327876,252.187522,207.963517,263.307067
1,1992_ALASKA,ALASKA,1992,920824.648047,1.049591e+06,1.067800e+05,7.207110e+05,2.221000e+05,9.724880e+05,4.983620e+05,...,9748.0,8789.000000,6714.000000,577954.717647,282069.084967,1.224870e+05,218.410116,266.360319,212.712256,258.859712
2,1992_ARIZONA,ARIZONA,1992,920824.648047,3.258079e+06,2.978880e+05,1.369815e+06,1.590376e+06,3.401580e+06,1.435908e+06,...,55433.0,49081.000000,37410.000000,577954.717647,282069.084967,6.734770e+05,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,920824.648047,1.711959e+06,1.785710e+05,9.587850e+05,5.746030e+05,1.743022e+06,9.643230e+05,...,34632.0,36011.000000,27651.000000,577954.717647,282069.084967,4.414900e+05,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,920824.648047,2.626002e+07,2.072470e+06,1.654651e+07,7.641041e+06,2.713883e+07,1.435892e+07,...,418418.0,363296.000000,270675.000000,577954.717647,282069.084967,5.254844e+06,208.398961,260.892247,196.764414,263.307067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,9.163662e+05,244.243515,288.172322,221.519266,262.720477
1914,2017_RHODE_ISLAND,RHODE_ISLAND,2017,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,9.163662e+05,237.554934,277.180126,223.353443,269.553823
1915,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,9.163662e+05,234.043993,274.673821,213.127835,265.767860
1916,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,9.163662e+05,241.588947,286.376160,221.750123,259.753002
1917,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,9.163662e+05,236.057019,273.415854,217.316396,271.617023

In [12]:
#9290764.951797385
df3.loc[df3['TOTAL_REVENUE']==9290764.951797385]

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
1275,1986_ALABAMA,ALABAMA,1986,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,56939.0,57261.000000,45396.000000,577954.717647,282069.084967,733735.000000,236.193347,279.500814,219.400783,263.689480
1276,1987_ALABAMA,ALABAMA,1987,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,56671.0,56472.000000,45742.000000,577954.717647,282069.084967,729234.000000,236.193347,279.500814,219.400783,263.689480
1277,1988_ALABAMA,ALABAMA,1988,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,57531.0,55262.000000,45571.000000,577954.717647,282069.084967,724751.000000,236.193347,279.500814,219.400783,263.689480
1278,1989_ALABAMA,ALABAMA,1989,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,59944.0,54912.000000,43482.000000,577954.717647,282069.084967,723743.000000,236.193347,279.500814,219.400783,263.689480
1279,1990_ALABAMA,ALABAMA,1990,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,58666.0,57024.000000,42031.000000,577954.717647,282069.084967,721806.000000,236.193347,279.500814,219.400783,263.689480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,916366.162555,244.243515,288.172322,221.519266,262.720477
1914,2017_RHODE_ISLAND,RHODE_ISLAND,2017,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,916366.162555,237.554934,277.180126,223.353443,269.553823
1915,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,916366.162555,234.043993,274.673821,213.127835,265.767860
1916,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,916366.162555,241.588947,286.376160,221.750123,259.753002
1917,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,917541.566176,9.290765e+06,787394.459967,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,69284.0,68324.391524,58768.074004,577954.717647,282069.084967,916366.162555,236.057019,273.415854,217.316396,271.617023

In [13]:
null_degerler(df3)
#df3.isnull().sum()/df3.isnull().count()

                              yüzde  adet
PRIMARY_KEY                     0.0     0
GRADES_PK_G                     0.0     0
AVG_READING_4_SCORE             0.0     0
AVG_MATH_8_SCORE                0.0     0
AVG_MATH_4_SCORE                0.0     0
GRADES_ALL_G                    0.0     0
GRADES_9_12_G                   0.0     0
GRADES_1_8_G                    0.0     0
GRADES_12_G                     0.0     0
GRADES_8_G                      0.0     0
GRADES_4_G                      0.0     0
GRADES_KG_G                     0.0     0
CAPITAL_OUTLAY_EXPENDITURE      0.0     0
STATE                           0.0     0
OTHER_EXPENDITURE               0.0     0
SUPPORT_SERVICES_EXPENDITURE    0.0     0
INSTRUCTION_EXPENDITURE         0.0     0
TOTAL_EXPENDITURE               0.0     0
LOCAL_REVENUE                   0.0     0
STATE_REVENUE                   0.0     0
FEDERAL_REVENUE                 0.0     0
TOTAL_REVENUE                   0.0     0
ENROLL                          0.0     0
YEAR                            0.0     0
AVG_READING_8_SCORE             0.0     0

In [14]:
# 4. SORU null olanlar enterpolasyon yapılarak dolduruldu.

In [15]:
df4=df.copy()
df_ort=pd.DataFrame()
df_ort=df4.groupby(by='YEAR').mean()
df_ort

,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,OTHER_EXPENDITURE,CAPITAL_OUTLAY_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
YEAR,,,,,,,,,,,,,,,,,,,,,
1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56782.980392,56269.686275,50990.509804,NaN,NaN,779473.960784,NaN,NaN,NaN,NaN
1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57600.705882,55657.117647,52565.196078,NaN,NaN,784474.764706,NaN,NaN,NaN,NaN
1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59813.843137,55941.313725,51954.392157,NaN,NaN,788013.529412,NaN,NaN,NaN,NaN
1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62394.078431,55950.274510,48495.647059,NaN,NaN,794955.039216,NaN,NaN,NaN,NaN
1990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63687.549020,58414.176471,46687.901961,NaN,NaN,808170.254902,NaN,NaN,NaN,NaN
1991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64998.549020,59217.058824,46910.901961,NaN,NaN,824448.588235,NaN,NaN,NaN,NaN
1992,NaN,4.572764e+06,2.970296e+05,2.088314e+06,2.187420e+06,4.653591e+06,2.454000e+06,1.370149e+06,NaN,4.050078e+05,...,65524.254902,61353.058824,47657.568627,NaN,NaN,839672.784314,218.410116,266.360319,212.712256,263.307067
1993,802054.333333,4.768758e+06,3.086224e+05,2.209300e+06,2.250836e+06,4.788283e+06,2.540431e+06,1.419870e+06,248234.784314,4.096238e+05,...,65904.117647,63711.098039,47530.019608,NaN,NaN,852253.254902,NaN,NaN,NaN,NaN
1994,801383.960784,4.916678e+06,3.272233e+05,2.225664e+06,2.363790e+06,4.954213e+06,2.626080e+06,1.476894e+06,262916.705882,4.041495e+05,...,67175.509804,64750.921569,48775.529412,NaN,NaN,864931.019608,NaN,NaN,NaN,NaN
1995,858973.039216,5.476034e+06,3.546117e+05,2.555041e+06,2.566381e+06,5.526114e+06,2.931096e+06,1.616281e+06,295324.647059,4.765508e+05,...,67266.333333,65810.549020,48767.352941,NaN,NaN,879225.117647,NaN,NaN,NaN,NaN
1996,873930.607843,5.744172e+06,3.647964e+05,2.737296e+06,2.642080e+06,5.838049e+06,3.076873e+06,1.680742e+06,303516.137255,5.445423e+05,...,67720.960784,66717.941176,50714.666667,NaN,NaN,894334.235294,221.479509,270.182528,214.587049,261.412097
1997,888379.745098,6.115397e+06,3.869910e+05,2.940125e+06,2.788281e+06,6.193357e+06,3.245567e+06,1.762159e+06,305274.705882,6.359637e+05,...,68773.666667,66963.019608,52410.431373,557507.058824,251767.843137,904448.960784,NaN,NaN,NaN,NaN
1998,897509.058824,6.504525e+06,4.272517e+05,3.140750e+06,2.936523e+06,6.595780e+06,3.427786e+06,1.873964e+06,318956.098039,7.034032e+05,...,70434.372549,68242.568627,53366.843137,563202.431373,254533.450980,912521.274510,NaN,NaN,NaN,NaN
1999,905101.470588,6.954543e+06,4.747857e+05,3.390289e+06,3.089468e+06,7.068126e+06,3.633184e+06,1.999630e+06,334733.431373,7.937301e+05,...,72281.686275,68568.176471,54541.588235,567115.549020,258153.529412,918767.627451,NaN,NaN,NaN,NaN
2000,910446.705882,7.443181e+06,5.229861e+05,3.650809e+06,3.269385e+06,7.572106e+06,3.883017e+06,2.136325e+06,352342.941176,8.755735e+05,...,72773.078431,69373.078431,54956.725490,572441.117647,261567.490196,925559.588235,224.803526,273.028605,217.612609,262.687292
2001,916296.274510,8.007941e+06,5.612788e+05,3.937915e+06,3.508747e+06,8.176763e+06,4.170963e+06,2.317517e+06,376510.254902,9.593529e+05,...,72448.901961,70900.764706,56134.490196,576228.549020,266215.372549,934606.549020,NaN,NaN,NaN,NaN
2002,923818.196078,8.363705e+06,6.412445e+05,4.066169e+06,3.656291e+06,8.680107e+06,4.408671e+06,2.452548e+06,396852.352941,1.037669e+06,...,71931.705882,72729.313725,58617.823529,578040.117647,272696.215686,944766.392157,NaN,NaN,NaN,NaN
2003,933396.862745,8.777804e+06,7.216835e+05,4.226496e+06,3.829624e+06,9.064218e+06,4.635866e+06,2.606806e+06,409705.098039,9.903809e+05,...,70962.529412,74694.725490,59735.117647,578290.941176,278219.627451,951768.921569,233.874626,276.743875,217.407252,262.503569
2004,938327.117647,9.225277e+06,8.098227e+05,4.276449e+06,4.139006e+06,9.436110e+06,4.807699e+06,2.715620e+06,422406.803922,1.024876e+06,...,70816.431373,74993.529412,60673.509804,577029.764706,284225.960784,956773.823529,NaN,NaN,NaN,NaN
2005,942259.960784,9.741954e+06,8.697107e+05,4.500507e+06,4.371736e+06,9.933855e+06,5.065459e+06,2.869167e+06,441206.921569,1.063179e+06,...,70147.176471,74546.921569,62357.803922,575350.588235,289959.843137,963005.843137,237.053410,277.751964,218.114082,261.774971
2006,947078.980392,1.039160e+07,9.235447e+05,4.760499e+06,4.707552e+06,1.052437e+07,5.330250e+06,3.058888e+06,463564.176471,1.153117e+06,...,70311.588235,73834.803922,64262.764706,575471.352941,293548.215686,966977.294118,NaN,NaN,NaN,NaN
2007,949109.254902,1.109366e+07,9.104578e+05,5.187230e+06,4.995971e+06,1.116970e+07,5.649631e+06,3.236339e+06,489835.686275,1.256719e+06,...,71066.313725,72724.607843,66166.901961,575978.960784,294013.058824,966481.549020,239.147568,280.617942,220.351554,262.154883
2008,949047.392157,1.160464e+07,9.229685e+05,5.508365e+06,5.173303e+06,1.185454e+07,5.975513e+06,3.449190e+06,511990.941176,1.346140e+06,...,71507.764706,72388.137255,66660.568627,575468.509804,292010.607843,965991.607843,NaN,NaN,NaN,NaN
2009,946249.313725,1.177812e+07,1.096081e+06,5.414781e+06,5.267262e+06,1.209353e+07,6.115512e+06,3.503797e+06,531834.450980,1.334207e+06,...,72559.411765,71593.647059,67287.960784,576271.509804,291407.862745,967862.392157,239.517404,282.416645,220.148958,263.478833
2010,946396.254902,1.182120e+07,1.450335e+06,5.053862e+06,5.317006e+06,1.205371e+07,6.219995e+06,3.508137e+06,532313.568627,1.163844e+06,...,72771.392157,71753.039216,68076.235294,580138.823529,290551.176471,970278.058824,NaN,NaN,NaN,NaN
2011,946587.745098,1.195207e+07,1.445229e+06,5.220582e+06,5.286261e+06,1.191374e+07,6.233568e+06,3.517628e+06,531916.490196,1.026307e+06,...,71997.352941,72139.431373,67683.843137,581545.941176,288354.607843,971013.117647,240.477019,283.490464,220.237258,264.824719
2012,945379.392157,1.185719e+07,1.167298e+06,5.302587e+06,5.387305e+06,1.185893e+07,6.207661e+06,3.526431e+06,531786.607843,9.843594e+05,...,72357.333333,72528.960784,68176.960784,584396.490196,288441.274510,975904.274510,NaN,NaN,NaN,NaN
2013,947012.176471,1.192289e+07,1.066444e+06,5.368678e+06,5.487767e+06,1.192948e+07,6.317421e+06,3.562444e+06,545102.784314,9.213200e+05,...,72700.647059,73595.235294,68159.450980,588303.725490,289055.470588,981265.137255,241.891073,283.914996,221.046820,266.680635
2014,948607.529412,1.232629e+07,1.037290e+06,5.663455e+06,5.625549e+06,1.224938e+07,6.481809e+06,3.681058e+06,556592.294118,9.333451e+05,...,72919.078431,73658.921569,68558.509804,590994.627451,291975.745098,986521.196078,NaN,NaN,NaN,NaN
2015,951263.450980,1.281705e+07,1.045230e+06,5.933968e+06,5.837854e+06,1.276276e+07,6.750863e+06,3.811953e+06,568480.588235,1.022395e+06,...,74367.352941,72912.980392,69357.490196,591894.117647,294129.019608,986804.215686,240.233705,281.759044,222.123041,265.007992
2016,952388.764706,1.337367e+07,1.061579e+06,6.234438e+06,6.077655e+06,1.326522e+07,7.011348e+06,3.911124e+06,587423.941176,1.120930e+06,...,75655.607843,73507.941176,70028.254902,593424.176471,295810.784314,991918.803922,NaN,NaN,NaN,NaN
2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75675.980392,73966.196078,71204.901961,NaN,296813.627451,993834.647059,239.202783,281.878993,221.095513,265.632094

In [16]:
for sutun_adi in df4.columns[3:]:
    df4[sutun_adi]=df4.loc[::][sutun_adi].interpolate(limit_direction='both')
    #df4.loc[:, sutun_adi].interpolate(inplace=True)

df4

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,727716.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,472847.0,208148.0,731634.0,208.327876,252.187522,207.963517,258.859712
1,1992_ALASKA,ALASKA,1992,727716.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,472847.0,208148.0,122487.0,211.790904,258.776900,207.088116,258.859712
2,1992_ARIZONA,ARIZONA,1992,727716.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,472847.0,208148.0,673477.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,727716.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,472847.0,208148.0,441490.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,727716.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,472847.0,208148.0,5254844.0,208.398961,260.892247,196.764414,265.519676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1913,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,159595.0,27361.0,94258.0,244.243515,288.172322,221.519266,262.720477
1914,2017_RHODE_ISLAND,RHODE_ISLAND,2017,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,159595.0,27361.0,94258.0,237.554934,277.180126,223.353443,269.553823
1915,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,159595.0,27361.0,94258.0,234.043993,274.673821,213.127835,265.767860
1916,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,159595.0,27361.0,94258.0,241.588947,286.376160,221.750123,259.753002
1917,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7537.0,7086.0,6405.0,159595.0,27361.0,94258.0,236.057019,273.415854,217.316396,271.617023

In [17]:
df4.loc[df['TOTAL_REVENUE']==2044669.0]

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
1274,2016_WYOMING,WYOMING,2016,94511.0,2044669.0,123012.0,1175899.0,745758.0,2034229.0,921494.0,...,7642.0,7135.0,6262.0,58998.0,26924.0,94170.0,233.931438,270.527222,217.836829,257.988094